name: Unit Tests

on:
  push:
    branches: [ 0.2-dev-ci-test ]
  pull_request:
    branches: [ 0.2-dev-ci-test ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t autompc .

    - name: Run tests
      run: |
        docker run --rm autompc coverage run -m unittest discover

   - name: Generate coverage report
      run: |
        docker run -t --rm -v "$(pwd)/coverage:/coverage" autompc coverage html -d /coverage/html

   - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/html